spring:
  application:
    name: iam-service

  datasource:
    url: jdbc:postgresql://localhost:5432/iam_bd
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true